sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
matrix:
  include:
    - language: python
      python: "3.7"
      dist: xenial
      sudo: true

install:
  - nvm install --lts
  - nvm use --lts
  - pip install -q tox coverage coveralls tox-travis

script:
  - coverage erase
  - tox

after_success:
  - coverage combine
  - coveralls

cache: pip

notifications:
  email:
    - boerni@gmail.com

before_deploy:
  - git stash --all
  - tox -e prepare_npm
_deploy_provider: &_deploy_provider
  skip_cleanup: true
  on:
    tags: true
    repo: ierror/django-js-reverse
    python: "3.7"
deploy:
  - <<: *_deploy_provider
    provider: pypi
    distributions: sdist bdist_wheel
    user: __token__
    password: $PYPI_TOKEN
  - <<: *_deploy_provider
    provider: npm
    email: django-js-reverse@graingert.co.uk
    api_key: $NPM_TOKEN
